
import java.awt.HeadlessException;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.DOMException;
import org.xml.sax.SAXException;

public class VentanaLeerXML extends javax.swing.JFrame {
    
    
    // Lista para almacenar las URLs y poder abrirlas después
    private final java.util.List<String> urls = new java.util.ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLeerXML.class.getName());


    
    public VentanaLeerXML() {
        initComponents();
        
        setLocationRelativeTo(null);    // Centrado de ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPeliculas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        btnVerTrailer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargar.setText("Cargar Películas");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        listaPeliculas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPeliculasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaPeliculas);

        txtDetalles.setColumns(20);
        txtDetalles.setRows(5);
        jScrollPane2.setViewportView(txtDetalles);

        btnVerTrailer.setText("Ver Tráiler");
        btnVerTrailer.setEnabled(false);
        btnVerTrailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTrailerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnVerTrailer)))
                .addGap(242, 242, 242))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btnVerTrailer)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        try {
            java.io.File archivo = new java.io.File("peliculas.xml");
            
            // Parsea el XML (DOM Estándar)
            javax.xml.parsers.DocumentBuilderFactory factory =
            javax.xml.parsers.DocumentBuilderFactory.newInstance();

            javax.xml.parsers.DocumentBuilder builder =
            factory.newDocumentBuilder();

            org.w3c.dom.Document doc = builder.parse(archivo);
            doc.getDocumentElement().normalize();

            org.w3c.dom.NodeList lista =
            doc.getElementsByTagName("pelicula");

            // Modelo para la JList visual
            javax.swing.DefaultListModel<String> modelo =
            new javax.swing.DefaultListModel<>();

            urls.clear();   // Limpia la lista de URLs vieja por si recargan

            
            // Recorre y extrae datos
            for (int i = 0; i < lista.getLength(); i++) {

                org.w3c.dom.Element e =
                (org.w3c.dom.Element) lista.item(i);

                // Extrae datos de los hijos
                String titulo = e.getElementsByTagName("titulo").item(0).getTextContent();
                String duracion = e.getElementsByTagName("duracion").item(0).getTextContent();
                String trailer = e.getElementsByTagName("trailer").item(0).getTextContent();

                modelo.addElement(titulo + " (" + duracion + " min)");

                urls.add(trailer);
            }
            
            // Asigna el modelo a la lista
            listaPeliculas.setModel(modelo);
            javax.swing.JOptionPane.showMessageDialog(this, "Películas perfectamente cargadas");
            
            
        } catch (HeadlessException | IOException | ParserConfigurationException | DOMException | SAXException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al leer el XML");
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void listaPeliculasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPeliculasValueChanged
        /* Cuando el usuario elige una película,
        se activa el botón para poder abrir el tráiler */
        int indice = listaPeliculas.getSelectedIndex();

        if (indice != -1) {
            btnVerTrailer.setEnabled(true);
        } else {
            btnVerTrailer.setEnabled(false);
        }
    }//GEN-LAST:event_listaPeliculasValueChanged

    private void btnVerTrailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTrailerActionPerformed
        try {
            int indice = listaPeliculas.getSelectedIndex();

            if (indice != -1) {
                String url = urls.get(indice);

                java.awt.Desktop.getDesktop().browse(
                        new java.net.URI(url));
            }

        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se pudo abrir el tráiler");
        }
    }//GEN-LAST:event_btnVerTrailerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaLeerXML().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnVerTrailer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaPeliculas;
    private javax.swing.JTextArea txtDetalles;
    // End of variables declaration//GEN-END:variables
}
