import javax.swing.JOptionPane;

public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());


    public VentanaPrincipal() {
        initComponents();
        
        setLocationRelativeTo(null);    // Centrado de ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCrearXML = new javax.swing.JMenuItem();
        menuLeerXML = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alta de Películas");

        jMenu1.setText("Funcionalidades");

        menuCrearXML.setText("Crear XML de Películas");
        menuCrearXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearXMLActionPerformed(evt);
            }
        });
        jMenu1.add(menuCrearXML);

        menuLeerXML.setText("Leer XML y Mostrar Tráiler");
        menuLeerXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLeerXMLActionPerformed(evt);
            }
        });
        jMenu1.add(menuLeerXML);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCrearXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearXMLActionPerformed
        // Abre la ventana para crear el XML
        VentanaCrearXML v = new VentanaCrearXML();
        v.setVisible(true);
    }//GEN-LAST:event_menuCrearXMLActionPerformed

    private void menuLeerXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLeerXMLActionPerformed
        // Antes de abrir la ventana comprueba si existe el archivo peliculas.xml
        java.io.File archivo = new java.io.File("peliculas.xml");

        if (!archivo.exists()) {
            JOptionPane.showMessageDialog(this, """
                                                El archivo peliculas.xml no existe 
                                                Debes de generarlo primero""");
            return;
        }

        // Si existe se abre la ventana de lectura
        VentanaLeerXML v = new VentanaLeerXML();
        v.setVisible(true);
    }//GEN-LAST:event_menuLeerXMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCrearXML;
    private javax.swing.JMenuItem menuLeerXML;
    // End of variables declaration//GEN-END:variables
}