import javax.swing.JOptionPane;

public class VentanaCrearXML extends javax.swing.JFrame {
    
    
    /* Listas para almacenar las películas por género
    He decidido usar tres listas separadas para controlar de
    manera más fácil el límite de 3 películas por cada género */
    private java.util.List<String> misterio = new java.util.ArrayList<>();
    private java.util.List<String> aventura = new java.util.ArrayList<>();
    private java.util.List<String> comedia = new java.util.ArrayList<>();

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCrearXML.class.getName());

  
    public VentanaCrearXML() {
        initComponents();
        
        setLocationRelativeTo(null);    // Centrado de ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboGenero = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTrailer = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLista = new javax.swing.JTextArea();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Género");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 47, 75, -1));

        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Misterio", "Aventura", "Comedia" }));
        getContentPane().add(comboGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 44, 107, -1));

        jLabel2.setText("Título");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 84, -1, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 84, 107, -1));

        jLabel3.setText("Duración(minutos)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 126, -1, -1));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 124, 107, -1));

        jLabel4.setText("URL del Tráiler");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 164, -1, -1));
        getContentPane().add(txtTrailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 164, 107, -1));

        btnAgregar.setText("AGREGAR PELÍCULA");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 188, -1, -1));

        txtLista.setColumns(20);
        txtLista.setRows(5);
        jScrollPane1.setViewportView(txtLista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 306, 562, 228));

        btnGenerar.setText("GENERAR XML");
        btnGenerar.setEnabled(false);
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 265, 137, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Se recogen los datos introducidos por el usuario
        String genero = comboGenero.getSelectedItem().toString();
        String titulo = txtTitulo.getText().trim();
        String duracionTexto = txtDuracion.getText().trim();
        String url = txtTrailer.getText().trim();

        // VALIDACIÓN: El título no puede estar vacío
        if (titulo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El título no puede estar vacío");
            return;
        }

        
        // VALIDACIÓN: Duración tiene que ser positivo o entero
        int duracion;
        try {
            duracion = Integer.parseInt(duracionTexto);
            if (duracion <= 0) {
                JOptionPane.showMessageDialog(this, "La duración debe ser un número positivo");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La duración debe ser un número entero válido");
            return;
        }

        // VALIDACIÓN: Una URL válida
        if (!url.startsWith("http://") && !url.startsWith("https://")) {
            JOptionPane.showMessageDialog(this, "La URL debe de empezar por http:// o https://");
            return;
        }

        
        // LÍMITE DE CONTROL: Máximo 3 por género
        java.util.List<String> listaSeleccionada = null;

        switch (genero) {
            case "Misterio" -> listaSeleccionada = misterio;
            case "Aventura" -> listaSeleccionada = aventura;
            case "Comedia" -> listaSeleccionada = comedia;
            default -> {
            }
        }

        // VALIDACIÓN: Número máximo de 3 películas
        if (listaSeleccionada.size() >= 3) {
            JOptionPane.showMessageDialog(this, "Ya existen 3 películas para el género " + genero);
            return;
        }

        
        // Se guardan los datos separados por barras |
        String pelicula = titulo + "|" + duracion + "|" + url;
        listaSeleccionada.add(pelicula);

        // Texto sacado al txtLista
        txtLista.append("Género: " + genero + "\n");
        txtLista.append("Título: " + titulo + "\n");
        txtLista.append("Duración: " + duracion + " minutos\n");
        txtLista.append("URL: " + url + "\n");
        txtLista.append("-----------------------------\n");

        // Limpia los campos para la siguiente
        txtTitulo.setText("");
        txtDuracion.setText("");
        txtTrailer.setText("");

        // COMPROBACIÓN: Si ya podemos activar el botón GENERAR XML
        // Solo si hay 3 en cada lista (9 en total)
        if (misterio.size() == 3 && aventura.size() == 3 && comedia.size() == 3) {
            btnGenerar.setEnabled(true);
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        /* Este método genera el archivo peliculas.xml usando la API DOM.
        Primero se construye el documento en memoria y después lo guardamos
        en la raíz del proyecto a través de un Transformer */


        // Comprobación de seguridad antes de generar el XML
        if (misterio.size() != 3 || aventura.size() != 3 || comedia.size() != 3) {
            JOptionPane.showMessageDialog(this, "Tiene que haber exactamente 3 películas por cada género");
            return;
        }
        
        try {
        // Se crea el documento XML en memoria usando DOM
            javax.xml.parsers.DocumentBuilderFactory factory =
            javax.xml.parsers.DocumentBuilderFactory.newInstance();

            javax.xml.parsers.DocumentBuilder builder =
            factory.newDocumentBuilder();

            org.w3c.dom.Document doc = builder.newDocument();
            
            // Nodo raíz <peliculas>
            org.w3c.dom.Element raiz = doc.createElement("peliculas");
            doc.appendChild(raiz);
            
            
            // PROCESO GÉNERO MISTERIO
            org.w3c.dom.Element nodoMisterio = doc.createElement("misterio");
            raiz.appendChild(nodoMisterio);
            
            for (String p : misterio) {
                String[] partes = p.split("\\|");

                org.w3c.dom.Element pelicula = doc.createElement("pelicula");

                org.w3c.dom.Element titulo = doc.createElement("titulo");
                titulo.setTextContent(partes[0]);

                org.w3c.dom.Element duracion = doc.createElement("duracion");
                duracion.setTextContent(partes[1]);

                org.w3c.dom.Element trailer = doc.createElement("trailer");
                trailer.setTextContent(partes[2]);

                pelicula.appendChild(titulo);
                pelicula.appendChild(duracion);
                pelicula.appendChild(trailer);

                nodoMisterio.appendChild(pelicula);
            }
            
            // PROCESO GÉNERO AVENTURA
            org.w3c.dom.Element nodoAventura = doc.createElement("aventura");
            raiz.appendChild(nodoAventura);

            for (String p : aventura) {
                String[] partes = p.split("\\|");

                org.w3c.dom.Element pelicula = doc.createElement("pelicula");

                org.w3c.dom.Element titulo = doc.createElement("titulo");
                titulo.setTextContent(partes[0]);

                org.w3c.dom.Element duracion = doc.createElement("duracion");
                duracion.setTextContent(partes[1]);

                org.w3c.dom.Element trailer = doc.createElement("trailer");
                trailer.setTextContent(partes[2]);

                pelicula.appendChild(titulo);
                pelicula.appendChild(duracion);
                pelicula.appendChild(trailer);

                nodoAventura.appendChild(pelicula);
            }

            
            // PROCESO GÉNERO AVENTURA
            org.w3c.dom.Element nodoComedia = doc.createElement("comedia");
            raiz.appendChild(nodoComedia);

            for (String p : comedia) {
                String[] partes = p.split("\\|");

                org.w3c.dom.Element pelicula = doc.createElement("pelicula");

                org.w3c.dom.Element titulo = doc.createElement("titulo");
                titulo.setTextContent(partes[0]);

                org.w3c.dom.Element duracion = doc.createElement("duracion");
                duracion.setTextContent(partes[1]);

                org.w3c.dom.Element trailer = doc.createElement("trailer");
                trailer.setTextContent(partes[2]);

                pelicula.appendChild(titulo);
                pelicula.appendChild(duracion);
                pelicula.appendChild(trailer);

                nodoComedia.appendChild(pelicula);
            }
            
            
            // Ahora se transforma el documento en un archivo XML real
            javax.xml.transform.TransformerFactory tf =
            javax.xml.transform.TransformerFactory.newInstance();
            // Esto hace que el XML salga con indentación bonita (saltos de línea)
            javax.xml.transform.Transformer transformer = tf.newTransformer();

            javax.xml.transform.dom.DOMSource origen =
                new javax.xml.transform.dom.DOMSource(doc);
            java.io.File archivo = new java.io.File("peliculas.xml");

            javax.xml.transform.stream.StreamResult destino =
                new javax.xml.transform.stream.StreamResult(archivo);

            transformer.transform(origen, destino);

            JOptionPane.showMessageDialog(this, "Se ha generado el archivo peliculas.xml");

            
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar el XML");
    }

    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaCrearXML().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextArea txtLista;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTrailer;
    // End of variables declaration//GEN-END:variables
}
